name: CI RS

on: [push]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1

jobs:
  ci-rs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14 ]
        rust-toolchain:
          - nightly
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
          enable-sccache: "true"

      - name: Run tests
        run: cargo test
      
      - name: Lint
        run: cargo clippy
      
      - name: Check formatting
        run: cargo fmt --check